### ISSUE TITLE
install_dev_tools does not make it clear when an installation has failed

### ISSUE THREAD

**Issue by KevinMGranger** [dora-metrics/pelorus#518]
While error messages are printed in the console, the functions continue past the error, resulting in yet more errors.

In addition, the failure to install one program is not propagated to the exit status.

This could be solved in two ways:

1. Manually propagate the error condition until the end of the script
2. Design the script so that it's meant to be used on one program at a time, and exit early when there's an error. It could still be invoked for each program using the makefile. This could even be parallelized!

**Comment by mpryc** [comment]
Checked and the issue is valid. It continues to run if the tool failed to be downloaded etc...
