### ISSUE TITLE
File extensions

### ISSUE THREAD

**Issue by mateusoliveira43** [dora-metrics/pelorus#684]
Hi everyone :wave:
Thanks for this awesome Project!

Pelorus have some files without extension. To get the list of files without extension, in the project root run 
```
find . -type f ! -name "?*.*" | grep -v "venv/\|git/"
```
Some of them should not have extension (like `.gitignore`), but I believe the Python files should, for example. This leads to the project quality checks not checking files properly.

For example, running `make black-check` does not warn of any errors today. But if we change the name of the file `scripts/bump-version` to `scripts/bump-version.py` and run `make black-check` again, black indicates format errors.

**Comment by mateusoliveira43** [comment]
A suggestion would be to add the scripts to the path (this can be done with console scripts section in `setup.cfg`, `setup.py` or `pyproject.toml` and running `pip install -e .`/`poetry install`) then the extension does not appear (and neither the folder) when running the command. 

An example https://github.com/mateusoliveira43/docky
if you `git clone` the repo and run `docky` (alias to `scripts/docky.py`), you will get a command not found error. But after running `pip install -e .`, `docky` would be available. The `pip install -e .` command could be added to `$(PELORUS_VENV)` command in makefile, to automatically adding the scripts to the path when configuring the development environment.

**Comment by KevinMGranger** [comment]
We can just add the extensions, I'm not a purist! I wouldn't mind setuptools integration eventually.

**Comment by mpryc** [comment]
Another approach to this is to have source files of the CLIs *with* extensions and link them to the CLIs executables *without*, so in our case, (example):

```shell
$ ls scripts/view-grafana-queries.py
scripts/view-grafana-queries.py

$ pushd scripts
$ mkdir src/
$ git mv scripts/view-grafana-queries.py scripts/src/
$ sed -i 's$../../charts/pelorus$../../../charts/pelorus$g' src/view-grafana-queries.py
$ ln -s ./src/view-grafana-queries.py ./view-grafana-queries
```

**Comment by KevinMGranger** [comment]
Not a bad idea. `setuptools` gets us those in the virtualenv for free, though.
