### ISSUE TITLE
Build and deploy of Pelorus operator test images in quay

### ISSUE THREAD

**Issue by mateusoliveira43** [dora-metrics/pelorus#881]
Features:
- For related PRs, GitHub actions should build and deploy Pelorus operator images:
  - `pelorus/rc-pelorus-operator-bundle`
  - `pelorus/rc-pelorus-operator`
  - `pelorus/rc-pelorus-exporter`

Requirements:
  - [x] changes to `exporters`, `charts` and `pelorus-operator` folder should trigger this job
  - [x] Tag images with PR number and commits (to identify them and avoid caching problems)
  - [x] OPTIONAL comment on PR when it finishes the deploy https://github.com/marketplace/actions/add-pr-comment
  - [ ] Remove images after PR closes

**Comment by mateusoliveira43** [comment]
I want to remove `pelorus-operator/` folder from our source code, but to make this task simpler, this will not be discussed now (to correctly generate operator files, [user must be logged in to RHOCP](https://sdk.operatorframework.io/docs/building-operators/helm/tutorial/#prerequisites)).
        
So, to trigger this CI job, developer has to change any file in `pelorus-operator/` folder (Michal is working in a PR that changing `charts/` folder, implies in changing `pelorus-operator/` folder). Changing exporters folder should also trigger, but user can change the exporters images with DEVELOPMENT configurations options. But think about creating exporter test image, our CI only builds them after PR closes today, right?

The steps will be:
- on pull_request conditions -> on workflow_run, podman login and push, comment PR
- on pull_request closed -> on workflow_run, podman login and delete

**Comment by weshayutin** [comment]
+1
