### ISSUE TITLE
Relocate the Pelorus github repo outside of konveyor

### ISSUE THREAD

**Issue by weshayutin** [dora-metrics/pelorus#887]
CNCF is requesting that Pelorus be moved out of the konveyor repo.

* best location atm is https://github.com/migtools/  unless we want our own org.

- [ ] https://github.com/dora-metrics/pelorus/pull/896
  - [x] test operator with `operator-sdk`
  - [x] dpulls app
  - [x] [dco app](https://github.com/apps/dco)
- [x] https://github.com/dora-metrics/pelorus/pull/910
- [x] https://github.com/konveyor/mig-demo-apps/pull/97
- [x] https://github.com/openshift/release/pull/37757
  - [x] https://docs.ci.openshift.org/docs/how-tos/onboarding-a-new-component/

**Comment by mateusoliveira43** [comment]
Commands to help us:

- `grep -Iinr "konveyor" .`

Related repositories to Pelorus:

- https://github.com/konveyor/pelorus
- https://github.com/konveyor/mig-demo-apps
- https://github.com/openshift/release
- https://github.com/redhat-openshift-ecosystem/community-operators-prod
