### ISSUE TITLE
Prometheus rework dicussion

### ISSUE THREAD

**Issue by mateusoliveira43** [dora-metrics/pelorus#939]
### Discussion

Prometheus has a limitation of just scrapping data that is **"new"** (max of 2 hours old?). We should define/document how we want to store/use data from exporters.

- Today, some exporters send data with defined timestamp, some do not. We should standardize this behavior.
  - allow user to choose between the behavior he wants? (document differences, pros and cons)
     - easy to maintain different use cases?
  - not specifying timestamp in metric
    - we can collect old data at any time (using it as the value of the metric, which does not use the benefices of Prometheus timeseries database store usage and stores unnecessary data)
    - more storage usage
  - specifying timestamp in metric
    - optimizes store usage
    - if data is not send fast (the 2 hours windows), then Prometheus will not store it.
- Allow Pelorus to be deployed using a standard database?
  - we would be able to send data at any time, but would not have Prometheus timeseries database store usage optimization
  - easy to integrate with grafana?
  - easy to maintain different use cases?
- also think about webhook use cases, if some workflow must be different

### Related to
 #932, #933, #934
 
 ### Requirements
 
 - [x] discussion between team members
 - [x] create issues for next steps

**Comment by mateusoliveira43** [comment]
Closing as https://github.com/dora-metrics/pelorus/issues/961 was created and accepted by team members

**Comment by PabloHiro** [comment]
I don't know if you welcome third party feedback, but just in case:

> * Allow Pelorus to be deployed using a standard database?
>     * we would be able to send data at any time, but would not have Prometheus timeseries database store usage optimization
>     * easy to integrate with grafana?
>     * easy to maintain different use cases?

Have you guys considered using InfluxDB as the backend to store metrics? Using a database (compatible with Grafana!) has the added advantage that metrics can be imported/exported so it is easier to showcase Pelorus to potential customers without having to keep it running for long periods of time.

When I install Pelorus I don't have a way to measure **past** DORA metrics before Pelorus was installed, but if I manage to process that information and load it in the DB I can visualize it now with Grafana

It would also solve the workarounds you are building around Prometheus limitation of ingesting metrics with older timestamps.

#933 
#943 
#961

**Comment by mateusoliveira43** [comment]
Yes, we do welcome third party feedback, @PabloHiro :smile: Thanks for sharing this with us

We have talked about using InfluxDB and another one that are compatible with Prometheus and Grafana.

For now, I believe we will keep using Prometheus, because some or the users trust it and use it. We should start adding the possibility to use another DB gradually.
