### ISSUE TITLE
Updating exporters images instead of creating new tag

### ISSUE THREAD

**Issue by mateusoliveira43** [dora-metrics/pelorus#966]
### OpenShift version

Not related to OpenShift

### Problem description

The last 2 runs of [Pelorus Exporter Build GitHub action job](https://github.com/dora-metrics/pelorus/actions/workflows/build-pelorus.yml) have updated v2.0.9 tag instead of creating new tag.

### Steps to reproduce

Merge PR touching `exporters` folder, but without updating charts version.

### Current behavior

Image is updated.

### Expected behavior

- [ ] A new tag should be created and previous version left untouched

### Code of Conduct

- [X] I agree to follow Pelorus's Code of Conduct

**Comment by mateusoliveira43** [comment]
@mpryc I checked out the job that generated it, and the image sha is `26742a6015cc986df25bbd87511ad1f222db6057`. Can you please link this sha to version `v2.0.9` of each exporter?

**Comment by mpryc** [comment]
Something didn't work as expected:

`v2.0.9` was tagged correctly, because it was the tag found in the chart versions, however the PR should not be accepted, because we already released `v2.0.9` meaning we should produce this PR with the version `v.2.0.10-rc.X`.
